// Generated by CoffeeScript 1.12.4
var isDev;

isDev = require("isDev");

if (isDev) {
  module.exports = (function() {
    var template;
    template = "return function anonymous() {\n  var args = createArgs(arguments, this);\n  return createInstance(arguments.callee, args, this);\n};";
    return function(name, createArgs, createInstance) {
      var createType;
      createType = Function("createInstance", "createArgs", template.replace("anonymous", name));
      return createType(createInstance, createArgs);
    };
  })();
} else {
  module.exports = function(name, createArgs, createInstance) {
    return function() {
      var args;
      args = createArgs(arguments, this);
      return createInstance(arguments.callee, args, this);
    };
  };
}
